# Generated by Django 5.0.1 on 2024-01-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyquotelist',
            name='quotes',
        ),
        migrations.AddField(
            model_name='monthlyquotelist',
            name='quotes',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
