# Generated by Django 5.0.1 on 2024-01-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotify', '0002_remove_monthlyquotelist_quotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyquotelist',
            name='quotes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
