# Generated by Django 5.0.1 on 2024-01-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotify', '0003_alter_monthlyquotelist_quotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
