# Generated by Django 5.0.3 on 2024-03-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotify', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveIndex(
            model_name='quote',
            name='quotify_quo_author__ec68f2_idx',
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
